name: autoport
description: AutoPort - Safe intercity ride-sharing platform
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^12.1.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1 