services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: autoport_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autoport
    ports:
      - "5433:5432"  # Changed from 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Application Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoport_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Database connection
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/autoport
      
      # JWT configuration (change these in production!)
      JWT_SECRET_KEY: your-secret-key-here-change-in-production
      JWT_ALGORITHM: HS256
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 30
      
      # Application settings
      APP_NAME: AutoPort API
      APP_VERSION: 0.1.0
      
      # Environment
      ENVIRONMENT: development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # Mount source code for development hot-reload
      # Remove this in production
      - ./:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data: